services:
  # 카프카 브로커 (Apache 공식 이미지 - KRaft 모드)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      # KRaft 모드 활성화 및 노드 설정
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      # Confluent KRaft 필수 설정 (임의의 고유 ID 지정)
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

      # 리스너 및 프로토콜 맵
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT

      # 컨트롤러 및 인터-브로커 통신 설정
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      # 복제 및 성능 설정 (싱글 노드 최적화)
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      # [필수] 데이터 유실 방지를 위한 이름이 있는 볼륨 설정
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka-net

  # 카프카 대시보드 (Kafka-UI)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-dashboard
    ports:
      - "8083:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kraft-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
      - DYNAMIC_CONFIG_ENABLED=true
      # Kafka Connect 연결 설정 추가
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=kafka-connect
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://kafka-connect:8083
    depends_on:
      - kafka
    networks:
      - kafka-net

  # Kafka Connect (Debezium MariaDB Connector 포함)
  kafka-connect:
    image: debezium/connect:2.7.3.Final
    container_name: kafka-connect
    ports:
      - "8084:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9094
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
    volumes:
      # 커넥트 역시 상태 정보 저장을 위해 볼륨을 잡아주는 것이 실무 관례입니다.
      - connect_data:/kafka/data
    depends_on:
      - kafka
      - kafka-ui
    networks:
      - kafka-net

volumes:
  kafka_data:
  connect_data:

networks:
  kafka-net:
    external: true