services:
  # 주문 서비스용 데이터베이스
  order-db:
    image: mariadb:latest
    container_name: order-db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: order_db
    volumes:
      - ./data/order:/var/lib/mysql
    # CDC를 위한 Binary Log 설정 추가
    command:
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --server-id=1
      - --binlog-do-db=order_db
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
    name: demo-multi_kafka-net