server:
  port: 8080

spring:
  datasource:
    # Docker Compose에서 설정한 3306 포트와 order_db 데이터베이스 사용
    url: jdbc:mariadb://localhost:3306/order_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # 엔티티 기반으로 테이블 자동 생성 및 수정
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      # 실행할 함수 빈 이름 정의
      definition: orderCompletedConsumer;orderFailedConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        # 출력 바인딩 (주문 생성 이벤트 발행)
        orderCreated-out-0:
          destination: order-created-topic
        # 입력 바인딩 (결제 완료 수신)
        orderCompletedConsumer-in-0:
          destination: order-completed-topic
          group: order-service-group
        # 입력 바인딩 (결제 실패 수신)
        orderFailedConsumer-in-0:
          destination: order-failed-topic
          group: order-service-group
#  kafka:
#    bootstrap-servers: localhost:9092
