server:
  port: 8082

spring:
  cloud:
    function:
      # 구독: point.completed
      definition: pointEventsConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        pointEventsConsumer-in-0:
          destination: point.events
          group: card-service-group
        # 통합된 카드 도메인 토픽으로 발행
        cardEvents-out-0:
          destination: card.events